name: Deploy to Prod

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:

  build_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discord_bot:prod
  clear_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Run the Docker image
      run: |
        docker stop discord_bot_live
        docker rm discord_bot_live
  list_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: List images
      run: docker image ls
  run_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Run the Docker image
      run: docker run -d -e $discord_bot_token --name discord_bot_live discord_bot:prod 
      env:
        discord_bot_token: ${{ secrets.test_discord_bot_token }}
