name: Deploy to Test

on:
  push:
    branches: 
      - test_*

jobs:

  build_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discord_bot:test
  clear_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Run the Docker image
      run: docker stop discord_bot_test && docker rm discord_bot_test
  list_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker image ls
  run_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Run the Docker image
      run: docker run -d -e $discord_bot_token --name discord_bot_test discord_bot:test 
      env:
        discord_bot_token: ${{ secrets.test_discord_bot_token }}
