name: Docker Image CI

on:
  push:
    branches: 
      - test_*

jobs:

  build_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discord_bot:$(date +%s)
  run_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker run -d -e $docker_bot_token discord_bot:$(date +%s)
      env:
        docker_bot_token: $${{ secrets.docker_bot_token }}
