name: Docker Image CI

on:
  push:
    branches: 
      - test_*

jobs:

  build_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discord_bot:test
  list_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker image ls
  run_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Run the Docker image
      run: docker run -d -e $discord_bot_token discord_bot:test
      env:
        discord_bot_token: ${{ secrets.test_discord_bot_token }}

on:
  push:
    branches: 
      - master
  pull-request:
    branches: 
      - master
jobs:

  build_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discord_bot:prod
  list_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker image ls
  run_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Run the Docker image
      run: docker run -d -e $discord_bot_token discord_bot:prod
      env:
        discord_bot_token: ${{ secrets.prod_discord_bot_token }}